name: agri_market
description: Agriculture Marketplace — Buyer & Seller Portal
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ── State management & routing
  get: ^4.7.3

  # ── Fonts
  google_fonts: ^8.0.2

  # ── UI & Charts
  fl_chart: ^1.2.0

  # ── Loading (skeleton / shimmer)
  shimmer: ^3.0.0

  # ── Country Selection
  csc_picker_plus: ^0.0.3


  # ── Image Selection
  image_picker: ^1.2.1


  # ── Audio Call
  flutter_webrtc: ^1.4.1

  # ── Utilities
  image: ^4.5.4
  intl: ^0.20.2
  uuid: ^4.5.3
  connectivity_plus: ^7.1.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/images/
    - assets/category/
    - assets/Mode Images/
    - assets/banner images/
    - assets/social icon/
