// GENERATED by tool/build_varieties_dart.dart — do not edit by hand.
import 'dart:convert';

Map<String, List<String>>? _productVarietiesCache;

Map<String, List<String>> productVarietiesByName() {
  return _productVarietiesCache ??=
      (jsonDecode(_productVarietiesJson) as Map<String, dynamic>)
          .map((k, v) => MapEntry(
            k,
            List<String>.from(v as List<dynamic>),
          ));
}

const String _productVarietiesJson = r'''
{
  "Acid Oil / Fatty Acid Distillate": [
    "Acid Oil (Soy)",
    "Acid Oil (Palm)",
    "Acid Oil (Blend)",
    "Fatty Acid Distillate (Palm)"
  ],
  "Agar / Carrageenan": [
    "Agar (Food Grade)",
    "Carrageenan (Kappa)",
    "Carrageenan (Iota)",
    "Carrageenan (Lambda)"
  ],
  "Alfalfa Meal": [
    "Alfalfa Meal (15% CP)",
    "Alfalfa Meal (17% CP)",
    "Dehydrated Alfalfa Pellets",
    "Sun-Cured Alfalfa"
  ],
  "Amaranth Grain": [
    "Golden Amaranth (A. hypochondriacus)",
    "Red Amaranth (A. cruentus)",
    "Plainsman"
  ],
  "Amylase": [
    "Alpha-Amylase (Bacterial)",
    "Alpha-Amylase (Fungal)"
  ],
  "Apple Pomace (Dried)": [
    "Apple Pomace (Sun-Dried)",
    "Apple Pomace (Dehydrated)",
    "Apple Pomace (Pellet)"
  ],
  "Astaxanthin": [
    "Astaxanthin (Synthetic 10%)",
    "Astaxanthin (Natural Haematococcus)",
    "Astaxanthin (Yeast)"
  ],
  "Astaxanthin (Natural, Haematococcus)": [
    "Astaxanthin Natural (Haematococcus pluvialis 2%)",
    "Astaxanthin Natural (5%)"
  ],
  "Astaxanthin (Synthetic)": [
    "Astaxanthin Synthetic (10%)",
    "Astaxanthin Synthetic (5%)"
  ],
  "Autolyzed Yeast": [
    "Autolyzed Yeast (Standard)",
    "Autolyzed Yeast (Spray-Dried)"
  ],
  "BHA (Butylated Hydroxyanisole)": [
    "BHA (Food Grade)",
    "BHA (Feed Grade)"
  ],
  "BHT (Butylated Hydroxytoluene)": [
    "BHT (Food Grade)",
    "BHT (Feed Grade)"
  ],
  "BSFL Oil": [
    "BSFL Oil (Crude)",
    "BSFL Oil (Refined)",
    "BSFL Oil (Lauric Acid Enriched)"
  ],
  "Bacillus subtilis": [
    "Bacillus subtilis (Standard)",
    "B. subtilis (Spore Form)",
    "Chr. Hansen BioPlus"
  ],
  "Bagasse": [
    "Bagasse (Fresh)",
    "Bagasse (Dried)",
    "Bagasse (Pellet)"
  ],
  "Baker's Yeast": [
    "Baker's Yeast (Active Dry)",
    "Baker's Yeast (Instant)"
  ],
  "Bakery Meal / Waste": [
    "Bakery Meal (Standard)",
    "Bakery Meal (Low Fat)",
    "Bakery Meal (High Sugar)"
  ],
  "Banana Flour / Peel": [
    "Banana Flour (Green Banana)",
    "Banana Peel Flour"
  ],
  "Barley": [
    "Two-Row (2R)",
    "Six-Row (6R)",
    "Hulless",
    "Waxy",
    "Malting",
    "Feed Grade"
  ],
  "Barley Bran": [
    "Hulled Barley Bran",
    "Pearl Barley Bran"
  ],
  "Barley Flour": [
    "Barley Flour (Fine)",
    "Barley Flour (Coarse)"
  ],
  "Beef Tallow": [
    "Beef Tallow (Edible Grade)",
    "Beef Tallow (Inedible)",
    "RBD Tallow"
  ],
  "Beetroot Powder": [
    "Beetroot Powder (Standard)",
    "Beetroot Powder (Organic)"
  ],
  "Bentonite": [
    "Sodium Bentonite (Fine)",
    "Calcium Bentonite",
    "Bentonite (Pellet Grade)"
  ],
  "Beta-1,3/1,6-Glucan": [
    "Beta-1",
    "3-Glucan",
    "Beta-1",
    "3/1",
    "6-Glucan (Yeast)",
    "Curdlan"
  ],
  "Beta-Carotene": [
    "Beta-Carotene (1% diluted)",
    "Beta-Carotene (10%)",
    "Beta-Carotene (Natural)"
  ],
  "Beta-Glucan": [
    "Beta-Glucan (Oat-derived)",
    "Beta-Glucan (Yeast-derived)"
  ],
  "Beta-Glucan (Yeast)": [
    "Beta-Glucan Yeast (Standard)",
    "Beta-Glucan (HP Yeast)"
  ],
  "Beta-glucanase": [
    "Beta-glucanase (Trichoderma)",
    "Beta-glucanase (Bacillus)"
  ],
  "Betaine (Natural)": [
    "Betaine Natural (Anhydrous)",
    "Betaine Natural (Monohydrate)"
  ],
  "Betaine HCl (Synthetic)": [
    "Betaine HCl (Standard)",
    "Betaine HCl (Feed Grade)"
  ],
  "Black Pepper": [
    "Black Pepper (Piper nigrum)",
    "Black Pepper (White)",
    "Black Pepper (Long)"
  ],
  "Black Soldier Fly Larvae Meal (BSFL)": [
    "BSFL Meal (Standard 40% CP)",
    "BSFL Meal (Full-Fat 50% CP)",
    "BSFL Meal (Defatted 55% CP)"
  ],
  "Blood Meal": [
    "Ring-Dried Blood Meal (RDBM)",
    "Flash-Dried Blood Meal (FDBM)",
    "Spray-Dried Blood Meal"
  ],
  "Bone Meal (Steamed)": [
    "Steamed Bone Meal 30% CP",
    "Steamed Bone Meal (Defatted)",
    "Bone Char"
  ],
  "Bread Crumbs": [
    "Bread Crumbs (Standard)",
    "Bread Crumbs (Fine)",
    "Bread Crumbs (Toasted)"
  ],
  "Brewer's Yeast (Dried)": [
    "Brewer's Yeast (Standard 44% CP)",
    "Brewer's Yeast (Debittered)",
    "Dried Brewer's Yeast (Organic)"
  ],
  "Brewers Yeast (Dried)": [
    "Brewers Yeast Dried (Standard)",
    "Brewers Yeast Debittered",
    "Brewers Yeast Autolyzed"
  ],
  "Broken Rice": [
    "Broken Rice (Long Grain)",
    "Broken Rice (Short Grain)",
    "Parboiled Broken",
    "Brewers Rice"
  ],
  "Buckwheat": [
    "Common Buckwheat (Fagopyrum esculentum)",
    "Tartary Buckwheat (F. tataricum)"
  ],
  "Butter / Butter Oil": [
    "Butter (Sweet Cream)",
    "Anhydrous Milkfat (AMF)",
    "Butter Oil"
  ],
  "Butyric Acid / Tributyrin": [
    "Butyric Acid (Free)",
    "Tributyrin (Glycerol Tributyrate)",
    "Na-Butyrate"
  ],
  "CMC": [
    "CMC (Low Viscosity)",
    "CMC (High Viscosity)"
  ],
  "CMC (Carboxymethyl Cellulose)": [
    "CMC (Low Viscosity)",
    "CMC (Medium Viscosity)",
    "CMC (High Viscosity)"
  ],
  "Camelina Meal": [
    "Camelina Meal (Standard)",
    "Camelina Meal (Low GLS)"
  ],
  "Canary Seed": [
    "Gluten-Free Canary Seed",
    "Regular Canary Seed",
    "Hulled"
  ],
  "Cane Juice": [
    "Cane Juice (Fresh)",
    "Cane Juice (Concentrated)"
  ],
  "Canola / Rapeseed Oil": [
    "Crude Canola Oil",
    "RBD Canola Oil",
    "High-Erucic Rapeseed Oil"
  ],
  "Canola Meal": [
    "Canola Meal 36% CP",
    "Canola Meal 38% CP (Low Glucosinolate)",
    "00-Canola Meal"
  ],
  "Canola Oil": [
    "Crude Canola Oil",
    "RBD Canola Oil",
    "High-Erucic Rapeseed Oil (HEAR)"
  ],
  "Canthaxanthin": [
    "Canthaxanthin (10%)",
    "Canthaxanthin (1% diluted)"
  ],
  "Carrageenan": [
    "Carrageenan (Kappa)",
    "Carrageenan (Iota)"
  ],
  "Carrot Powder": [
    "Carrot Powder (Standard)",
    "Carrot Powder (Organic)"
  ],
  "Carvacrol": [
    "Carvacrol (Standard 85%)",
    "Carvacrol (HP 98%)"
  ],
  "Casein": [
    "Acid Casein",
    "Rennet Casein",
    "Micellar Casein"
  ],
  "Cassava Chips (Dried)": [
    "Cassava Chips (Thailand)",
    "Cassava Chips (Vietnam)",
    "Cassava Chips (Africa)"
  ],
  "Cassava Flour": [
    "Cassava Flour (Fine)",
    "Cassava Flour (Coarse / Garri)"
  ],
  "Cassava Peels (Dried)": [
    "Cassava Peels (Sun-Dried)",
    "Cassava Peels (Oven-Dried)"
  ],
  "Cassava Pellets": [
    "Cassava Pellets (Standard 65%)",
    "Cassava Pellets (High-Starch 68%)"
  ],
  "Cassava Starch": [
    "Native Cassava Starch",
    "Modified Cassava Starch",
    "Oxidized Cassava Starch"
  ],
  "Cell-Cultured Protein": [
    "Cell-Cultured Protein (Avian)",
    "Cell-Cultured Protein (Porcine)",
    "Cell-Cultured Protein (Bovine)"
  ],
  "Cellulase": [
    "Cellulase (Trichoderma reesei)",
    "Cellulase (Aspergillus)"
  ],
  "Chickpea Protein": [
    "Chickpea Protein Concentrate (65%)",
    "Chickpea Protein Isolate (80%)"
  ],
  "Chickpeas / Garbanzo Beans": [
    "Kabuli Chickpea",
    "Desi Chickpea",
    "Black Chickpea"
  ],
  "Chili / Capsicum": [
    "Chili Powder (Cayenne)",
    "Capsicum Oleoresin",
    "Chili (Bird's Eye)"
  ],
  "Chlorella": [
    "Chlorella vulgaris (Standard)",
    "Chlorella pyrenoidosa"
  ],
  "Choice White Grease (CWG)": [
    "CWG (Standard)",
    "CWG (Bleached)"
  ],
  "Choline Chloride": [
    "Choline Chloride (60% on carrier)",
    "Choline Chloride (50% liquid)"
  ],
  "Chromium Picolinate": [
    "Chromium Picolinate (Standard)",
    "Chromium Nicotinate"
  ],
  "Cinnamaldehyde": [
    "Cinnamaldehyde (Standard 95%)",
    "Cinnamaldehyde (Pharma Grade)"
  ],
  "Cinnamon Powder": [
    "Cinnamon (Cassia)",
    "Cinnamon (Ceylon)",
    "Cinnamon (Saigon)"
  ],
  "Citrus Pulp (Dried)": [
    "Citrus Pulp Dried (Standard)",
    "Citrus Pulp Pellets",
    "Orange Pulp",
    "Lemon Pulp"
  ],
  "Cobalt Sulfate": [
    "Cobalt Sulfate (Monohydrate)",
    "Cobalt Carbonate"
  ],
  "Cocoa Husks": [
    "Cocoa Husks (Dried)",
    "Cocoa Shell Meal"
  ],
  "Cocoa Pod Husk": [
    "Cocoa Pod Husk (Dried)",
    "Cocoa Pod Husk (Fermented)"
  ],
  "Coconut Oil": [
    "Coconut Oil (Crude)",
    "Coconut Oil (RBD)",
    "Virgin Coconut Oil"
  ],
  "Coffee Husks": [
    "Coffee Husks (Dried)",
    "Coffee Husks (Ground)"
  ],
  "Common Salt (NaCl)": [
    "Salt (Iodized)",
    "Salt (Non-Iodized)",
    "Salt (Fine)",
    "Salt (Coarse)"
  ],
  "Cookie / Biscuit Waste": [
    "Cookie Waste (Standard)",
    "Biscuit Waste (Cream Filled)"
  ],
  "Copper Proteinate": [
    "Copper Proteinate (Bioplex Cu)",
    "Copper Lysinate"
  ],
  "Copper Sulfate": [
    "Copper Sulfate (Pentahydrate)",
    "Copper Sulfate (Anhydrous)"
  ],
  "Copra Meal": [
    "Copra Meal (Expeller 20% CP)",
    "Copra Meal (Solvent 22% CP)"
  ],
  "Corn Fiber": [
    "Corn Fiber (Standard)",
    "Corn Fiber (Modified)"
  ],
  "Corn Gluten Feed": [
    "Corn Gluten Feed (Dry)",
    "Corn Gluten Feed (Wet)"
  ],
  "Corn Gluten Meal": [
    "Corn Gluten Meal 60%",
    "Corn Gluten Meal 41%"
  ],
  "Corn Oil": [
    "Corn Oil (Crude)",
    "Corn Oil (RBD)"
  ],
  "Corn Starch": [
    "Corn Starch (Native)",
    "Corn Starch (Waxy)",
    "Corn Starch (High-Amylose)"
  ],
  "Corn Steep Liquor": [
    "Corn Steep Liquor (Standard)",
    "CSL (Low Lactic Acid)",
    "CSL (Concentrated)"
  ],
  "Cottonseed Cake": [
    "Cottonseed Cake (40% CP)",
    "Cottonseed Cake (36% CP)"
  ],
  "Cottonseed Hulls": [
    "Cottonseed Hulls (Coarse)",
    "Cottonseed Hulls (Ground)"
  ],
  "Cottonseed Meal": [
    "Cottonseed Meal (Solvent)",
    "Cottonseed Meal (Expeller)",
    "Glandless Cottonseed Meal"
  ],
  "Cottonseed Oil": [
    "Cottonseed Oil (Crude)",
    "Cottonseed Oil (RBD)"
  ],
  "Cowpeas": [
    "Black-Eyed Pea (Cowpea)",
    "Cream Cowpea",
    "Brown Cowpea"
  ],
  "Crab Meal": [
    "Crab Meal (Whole)",
    "Crab Meal (Shell Meal)",
    "Blue Crab Meal"
  ],
  "Cricket Meal": [
    "Cricket Meal (Standard)",
    "Cricket Meal (Dried/Ground)"
  ],
  "Crude Palm Oil (CPO)": [
    "CPO (Standard)",
    "RBD Palm Oil",
    "Palm Olein",
    "Palm Stearin"
  ],
  "Cumin / Jeera": [
    "Cumin (Black Jeera)",
    "Cumin (White Jeera)",
    "Cumin (Seed)"
  ],
  "DDGS (Barley)": [
    "DDGS Barley (Standard)",
    "DDGS Barley (HP)"
  ],
  "DDGS (Corn, Distillers Dried Grains with Solubles)": [
    "DDGS Corn (Standard 27% CP)",
    "DDGS Corn (HP 30% CP)",
    "DDGS Corn (Low Fat)"
  ],
  "DDGS (Wheat)": [
    "DDGS Wheat (Standard)",
    "DDGS Wheat (HP)"
  ],
  "DL-Methionine": [
    "DL-Methionine (99%)",
    "Liquid DL-Methionine",
    "Methionine Hydroxy Analogue (MHA)"
  ],
  "Dicalcium Phosphate (DCP)": [
    "DCP (Feed Grade 18% P)",
    "DCP (Technical Grade)"
  ],
  "Dimethyl Sulfoxide (DMSO)": [
    "DMSO (Technical Grade)",
    "DMSO (Pharmaceutical Grade)"
  ],
  "Dried Beet Pulp": [
    "Dried Beet Pulp (Shreds)",
    "Dried Beet Pulp (Pellets)",
    "Molassed Beet Pulp"
  ],
  "Dried Brewers Grains": [
    "Dried Brewers Grains (Standard 27% CP)",
    "DBG (Low Fat)"
  ],
  "Dried Lucerne / Hay": [
    "Dried Lucerne (Standard)",
    "Lucerne Hay (Baled)"
  ],
  "Dried Potato Flakes": [
    "Dried Potato Flakes (Standard)",
    "Instant Potato Flakes"
  ],
  "Dried Whey": [
    "Dried Whey (Standard)",
    "Delactosed Whey",
    "Demineralized Whey"
  ],
  "Dried Whole Egg": [
    "Dried Whole Egg (Standard)",
    "Dried Whole Egg (Organic)"
  ],
  "Duckweed Meal": [
    "Duckweed Meal (Lemna)",
    "Duckweed Meal (Wolffia)",
    "Duckweed Meal (Spirodela)"
  ],
  "Egg White Powder / Albumen": [
    "Egg Albumen (Spray-Dried)",
    "Egg Albumen (Freeze-Dried)"
  ],
  "Egg Yolk Powder": [
    "Egg Yolk Powder (Standard)",
    "Egg Yolk Powder (Freeze-Dried)"
  ],
  "Ethoxyquin (EQ)": [
    "Ethoxyquin (EQ) 66%",
    "EQ 33% (Diluted)"
  ],
  "FOS (Fructo-Oligosaccharides)": [
    "FOS (Short Chain scFOS)",
    "FOS (Long Chain lcFOS)"
  ],
  "Feather Meal (Hydrolyzed)": [
    "Hydrolyzed Feather Meal 80% CP",
    "Enzymatically Hydrolyzed Feather Meal"
  ],
  "Fermented Soybean Meal": [
    "Fermented SBM (Standard)",
    "Fermented SBM (HP, 55% CP)"
  ],
  "Ferrous Sulfate": [
    "Ferrous Sulfate (Monohydrate)",
    "Ferrous Sulfate (Heptahydrate)"
  ],
  "Field Beans / Faba Beans": [
    "Faba Bean (Tannin-Free)",
    "Faba Bean (High-Tannin)",
    "Horse Bean"
  ],
  "Field Peas": [
    "Field Pea (Yellow)",
    "Field Pea (Green)",
    "Field Pea (Maple)"
  ],
  "Filter Cake / Press Mud": [
    "Filter Cake (Fresh)",
    "Filter Cake (Dried / Press Mud)"
  ],
  "Fish Meal (Anchovy, 65% CP)": [
    "FM Anchovy 65% CP (Peru)",
    "FM Anchovy 60% CP",
    "LT Anchovy FM"
  ],
  "Fish Meal (Catfish By-Product)": [
    "Catfish By-Product Meal (Standard)",
    "Catfish By-Product Meal (Dried)"
  ],
  "Fish Meal (Herring)": [
    "FM Herring (Norway)",
    "FM Herring (Iceland)",
    "FM Herring LT"
  ],
  "Fish Meal (Low Temperature, LT)": [
    "LT Fish Meal 65% CP",
    "LT Fish Meal 67% CP"
  ],
  "Fish Meal (Menhaden)": [
    "FM Menhaden 65% CP (USA)",
    "FM Menhaden 60% CP"
  ],
  "Fish Meal (Sardine)": [
    "FM Sardine (Japan/EU)",
    "FM Sardine 65% CP",
    "FM Sardine LT"
  ],
  "Fish Meal (Super Prime)": [
    "Super Prime FM 68% CP (Peru)",
    "Super Prime FM 70% CP"
  ],
  "Fish Meal (Tilapia By-Product)": [
    "Tilapia By-Product Meal (Standard)",
    "Tilapia By-Product Meal (Dried)"
  ],
  "Fish Oil (Anchovy)": [
    "Fish Oil Anchovy (Crude)",
    "Fish Oil Anchovy (Refined)"
  ],
  "Fish Oil (Menhaden)": [
    "Fish Oil Menhaden (Crude)",
    "Fish Oil Menhaden (Refined)"
  ],
  "Fish Oil (Refined, EPA/DHA enriched)": [
    "Refined Fish Oil (EPA/DHA >30%)",
    "Refined Fish Oil (EPA/DHA >50%)",
    "MEG-3 Enriched"
  ],
  "Fish Oil (Salmon)": [
    "Fish Oil Salmon (Crude)",
    "Fish Oil Salmon (Refined)"
  ],
  "Fish Protein Hydrolysate (FPH)": [
    "FPH (Liquid)",
    "FPH (Spray-Dried Powder)",
    "FPH (Deodorized)"
  ],
  "Fish Solubles (Condensed)": [
    "Fish Solubles (Standard)",
    "Fish Solubles (Concentrated >50%)"
  ],
  "Full-Fat Soybean (Extruded)": [
    "Extruded Full-Fat SBM (Non-GMO)",
    "Extruded Full-Fat SBM (GMO)"
  ],
  "Fulvic Acids": [
    "Fulvic Acid (Standard)",
    "Potassium Fulvate"
  ],
  "Garlic Extract (Allicin)": [
    "Garlic Extract Allicin (Standard)",
    "Garlic Extract (Stabilized)"
  ],
  "Garlic Powder": [
    "Garlic Powder (Standard)",
    "Garlic Granules",
    "Garlic Oil"
  ],
  "Ginger Powder": [
    "Ginger Powder (Zingiber officinale)",
    "Ginger Oleoresin"
  ],
  "Glucose / Dextrose": [
    "Glucose Monohydrate",
    "Anhydrous Dextrose",
    "Liquid Glucose"
  ],
  "Glycerol / Glycerine (Crude)": [
    "Crude Glycerol (80%)",
    "Crude Glycerol (88%)",
    "Crude Glycerol (Biodiesel)"
  ],
  "Glycine": [
    "Glycine (Feed Grade 99%)",
    "Glycine (Technical)"
  ],
  "Grape Pomace": [
    "Grape Pomace (White)",
    "Grape Pomace (Red)",
    "Grape Seed Meal"
  ],
  "Groundnut Cake (Expeller)": [
    "Groundnut Cake 42% CP",
    "Groundnut Cake 45% CP"
  ],
  "Groundnut Hulls": [
    "Groundnut Hulls (Raw)",
    "Groundnut Hulls (Ground)"
  ],
  "Groundnut Meal": [
    "Groundnut Meal (Solvent 48% CP)",
    "Groundnut Meal (Expeller 44% CP)",
    "Aflatoxin-Free Certified"
  ],
  "Groundnut Oil": [
    "Crude Groundnut Oil",
    "RBD Groundnut Oil"
  ],
  "Guar Gum": [
    "Guar Gum (Regular)",
    "Guar Gum (Fast-Hydrating)"
  ],
  "Guar Meal": [
    "Guar Meal (Refined)",
    "Guar Meal (Crude)",
    "Guar Korma"
  ],
  "Hemp Protein Meal": [
    "Hemp Protein Meal (40% CP)",
    "Hemp Protein Meal (50% CP)"
  ],
  "Hominy Feed": [
    "Hominy Feed (Standard)",
    "Hominy Feed (Coarse)"
  ],
  "Hops Residue": [
    "Hops Residue (Spent Hops)",
    "Hops Pellet Residue"
  ],
  "Housefly Larvae Meal": [
    "Housefly Larvae Meal (Standard)"
  ],
  "Humic Acids": [
    "Humic Acid (Leonardite)",
    "Humic Acid (Lignite)",
    "Potassium Humate"
  ],
  "Hydrolyzed Leather Meal": [
    "Hydrolyzed Leather Meal (Standard)"
  ],
  "Inosine Monophosphate (IMP)": [
    "IMP (Feed Grade)",
    "IMP (Food Grade)"
  ],
  "Inositol": [
    "Inositol (Feed Grade)",
    "Inositol (Pharm Grade)"
  ],
  "Iodine (Potassium Iodide)": [
    "Potassium Iodide (KI)",
    "Calcium Iodate (Ca(IO3)2)"
  ],
  "Iron Proteinate": [
    "Iron Proteinate (Bioplex Fe)",
    "Iron Glycinate"
  ],
  "Krill Meal": [
    "Krill Meal (Antarctic, E. superba)",
    "Krill Meal (North Pacific)"
  ],
  "Krill Oil": [
    "Krill Oil (Phospholipid-rich)",
    "Krill Oil (Refined)",
    "RIMFROST Krill Oil"
  ],
  "L-Arginine": [
    "L-Arginine (98%)",
    "L-Arginine HCl"
  ],
  "L-Glutamine": [
    "L-Glutamine (Feed Grade 98%)",
    "L-Glutamine (Pharmaceutical)"
  ],
  "L-Isoleucine": [
    "L-Isoleucine (98%)",
    "L-Isoleucine (Feed Grade)"
  ],
  "L-Leucine": [
    "L-Leucine (98%)",
    "L-Leucine (Feed Grade)"
  ],
  "L-Lysine HCl": [
    "L-Lysine HCl (98.5%)",
    "L-Lysine Sulfate (65%)",
    "L-Lysine Liquid"
  ],
  "L-Threonine": [
    "L-Threonine (98.5%)",
    "L-Threonine (Feed Grade)"
  ],
  "L-Tryptophan": [
    "L-Tryptophan (98%)",
    "L-Tryptophan (Feed Grade)"
  ],
  "L-Valine": [
    "L-Valine (98.5%)",
    "L-Valine (Feed Grade)"
  ],
  "Lactobacillus acidophilus": [
    "Lactobacillus acidophilus (Standard)",
    "L. acidophilus (Freeze-Dried)"
  ],
  "Lactose": [
    "Lactose (Feed Grade)",
    "Lactose Monohydrate (Pharma Grade)"
  ],
  "Lard": [
    "Lard (Edible)",
    "Lard (Feed Grade)"
  ],
  "Lard / Pork Fat": [
    "Lard (Edible)",
    "Lard (Feed Grade)",
    "Pork Fat (Refined)"
  ],
  "Lentils": [
    "Red Lentil",
    "Green Lentil",
    "Brown Lentil",
    "Black Lentil (Beluga)"
  ],
  "Lignosulfonate": [
    "Lignosulfonate (Calcium)",
    "Lignosulfonate (Sodium)",
    "Lignosulfonate (Magnesium)"
  ],
  "Limestone Flour (CaCO3)": [
    "Limestone Fine (< 1mm)",
    "Limestone Coarse (1-3mm)",
    "Limestone Pellet"
  ],
  "Linseed Cake": [
    "Linseed Cake (30% CP)",
    "Linseed Cake (36% CP)"
  ],
  "Linseed Meal": [
    "Linseed Meal (Solvent 34% CP)",
    "Linseed Meal (Expeller 30% CP)"
  ],
  "Linseed Oil": [
    "Raw Linseed Oil",
    "Refined Linseed Oil",
    "Boiled Linseed Oil"
  ],
  "Lipase": [
    "Lipase (Fungal)",
    "Lipase (Microbial)",
    "Lipase (Pancreatic)"
  ],
  "Lupins (Sweet)": [
    "White Lupin (L. albus)",
    "Yellow Lupin (L. luteus)",
    "Narrow-Leaf Lupin (L. angustifolius)"
  ],
  "Lutein": [
    "Lutein (Marigold extract 5%)",
    "Lutein (Saponified 20%)"
  ],
  "MOS (Mannan-Oligosaccharides)": [
    "MOS (Standard)",
    "MOS (ActiMOS)",
    "Bio-MOS"
  ],
  "Magnesium Oxide (MgO)": [
    "Magnesium Oxide (Caustic)",
    "Magnesium Oxide (Dead-Burned)",
    "Magnesium Oxide (Calcined)"
  ],
  "Maize / Corn": [
    "Yellow Dent",
    "White Dent",
    "Waxy",
    "Flint",
    "Sweet",
    "Popcorn",
    "Blue",
    "High-Oil",
    "High-Lysine",
    "QPM (Quality Protein Maize)"
  ],
  "Maize Bran": [
    "Maize Bran (Coarse)",
    "Maize Bran (Fine)",
    "Hominy Bran"
  ],
  "Maize Flour": [
    "Maize Flour (Fine)",
    "Maize Flour (Coarse / Grits)"
  ],
  "Maize Germ": [
    "Maize Germ (Defatted)",
    "Maize Germ (Full-Fat)"
  ],
  "Malt Culms / Sprouts": [
    "Malt Culms (Standard)",
    "Malt Sprouts (Dried)"
  ],
  "Manganese Methionine": [
    "Manganese Methionine (Availa-Mn)",
    "Manganese Methionine Complex"
  ],
  "Manganese Sulfate": [
    "Manganese Sulfate (Monohydrate)",
    "Manganese Sulfate (Heptahydrate)"
  ],
  "Mango Kernel Flour": [
    "Mango Kernel Flour (Standard)",
    "Mango Kernel Flour (Defatted)"
  ],
  "Mealworm Meal (Tenebrio molitor)": [
    "Mealworm Meal (Standard 53% CP)",
    "Mealworm Meal (Defatted 60% CP)"
  ],
  "Mealworm Oil": [
    "Mealworm Oil (Crude)",
    "Mealworm Oil (Refined)"
  ],
  "Meat Meal": [
    "Meat Meal 55% CP",
    "Meat Meal 50% CP"
  ],
  "Meat and Bone Meal (MBM)": [
    "MBM 40% CP",
    "MBM 45% CP",
    "MBM 50% CP (EU Grade)",
    "MBM (Australia)",
    "MBM (USA)"
  ],
  "Milk Replacer": [
    "Milk Replacer (Calf)",
    "Milk Replacer (Piglet)",
    "Milk Replacer (Lamb)"
  ],
  "Millet (Finger / Ragi)": [
    "African Finger Millet",
    "Ragi Local",
    "CO-15",
    "GPU-28",
    "VR-708"
  ],
  "Millet (Pearl)": [
    "ICTP 8203",
    "Tifleaf 3",
    "HHB 67",
    "Bajra Hybrid",
    "Composite"
  ],
  "Modified Starch": [
    "Modified Starch (Waxy Maize)",
    "Modified Starch (Potato)",
    "Modified Starch (Tapioca)"
  ],
  "Modified Starch (Waxy Maize)": [
    "Modified Starch Waxy Maize (Standard)",
    "Waxy Maize (Pregelatinized)"
  ],
  "Molasses (Sugarcane)": [
    "Sugarcane Molasses (A-Molasses)",
    "Sugarcane Molasses (B-Molasses)",
    "Blackstrap Molasses"
  ],
  "Monocalcium Phosphate (MCP)": [
    "MCP (Feed Grade 22% P)",
    "MCP (Technical)"
  ],
  "Moringa Leaf Meal": [
    "Moringa Leaf Meal (M. oleifera)",
    "Moringa Seed Cake"
  ],
  "Mung Beans": [
    "Mung Bean (Green)",
    "Mung Bean (Golden)",
    "Mung Bean (Black)"
  ],
  "Mustard Seed Cake": [
    "Mustard Cake (Yellow)",
    "Mustard Cake (Brown/Black)"
  ],
  "Mycoprotein (Quorn)": [
    "Mycoprotein Quorn (Standard)",
    "Mycoprotein (Fusarium venenatum)"
  ],
  "Nannochloropsis": [
    "Nannochloropsis gaditana",
    "Nannochloropsis oculata",
    "Nannochloropsis salina"
  ],
  "Natural Vitamin E (Tocopherol)": [
    "Natural Vit-E (d-Alpha Tocopherol)",
    "Natural Vit-E (Mixed Tocopherols)"
  ],
  "Nucleotides": [
    "Nucleotides (Yeast-derived)",
    "Nucleotides (Fermentation-derived)"
  ],
  "Nucleotides (Feed Grade)": [
    "Nucleotides (Standard Feed Grade)",
    "Nucleotides (HP Aqua Grade)"
  ],
  "Oat Bran": [
    "Oat Bran (Fine)",
    "Oat Bran (Coarse)",
    "Toasted Oat Bran"
  ],
  "Oat Feed": [
    "Oat Feed (Coarse)",
    "Oat Feed (Fine)",
    "Oat Mill By-Product"
  ],
  "Oat Hulls": [
    "Oat Hulls (Raw)",
    "Oat Hulls (Ground)"
  ],
  "Oats": [
    "Common White Oat",
    "Red Oat",
    "Naked/Hulless Oat",
    "Black Oat",
    "Spring Oat",
    "Winter Oat"
  ],
  "Oregano Powder": [
    "Oregano (Origanum vulgare)",
    "Oregano (Mexican)",
    "Oregano (Greek)"
  ],
  "Organic Acids (Formic, Propionic)": [
    "Formic Acid 85%",
    "Propionic Acid 99%",
    "Blend (Formic+Propionic)"
  ],
  "Organic Selenium": [
    "Organic Selenium (Selenomethionine)",
    "Organic Se (Yeast-bound)"
  ],
  "Oyster Shell Flour": [
    "Oyster Shell (Fine)",
    "Oyster Shell (Coarse)"
  ],
  "Oyster Shell Meal": [
    "Oyster Shell Meal (Fine)",
    "Oyster Shell Meal (Coarse)",
    "Calcite"
  ],
  "Palm Kernel Cake (PKC)": [
    "PKC (Expeller)",
    "PKC (Solvent)",
    "PKC (Pellet)"
  ],
  "Palm Kernel Meal": [
    "PKM (Standard)",
    "PKM (Defatted)"
  ],
  "Palm Kernel Oil": [
    "Crude Palm Kernel Oil",
    "RBD Palm Kernel Oil"
  ],
  "Palm Oil (RBD)": [
    "CPO (Raw)",
    "RBD Palm Oil",
    "Palm Olein",
    "Palm Stearin"
  ],
  "Palm Oil Sludge / POME": [
    "Palm Oil Mill Effluent (POME)",
    "Decanter Cake",
    "Palm Sludge Oil"
  ],
  "Pasta Waste": [
    "Pasta Waste (Wheat)",
    "Pasta Waste (Semolina)"
  ],
  "Pea Hull / Fibre": [
    "Pea Hull (Raw)",
    "Pea Hull (Pellet)"
  ],
  "Pea Protein Concentrate": [
    "Pea Protein Conc. 65% CP",
    "Pea Protein Conc. 80% CP"
  ],
  "Pea Starch": [
    "Pea Starch (Native)",
    "Pea Starch (Modified)"
  ],
  "Phytase": [
    "Phytase (E. coli derived)",
    "Phytase (Aspergillus niger)",
    "Phytase (Peniophora lycii)",
    "Ronozyme HiPhos"
  ],
  "Pigeon Peas (Toor Dal)": [
    "Pigeon Pea (Desi)",
    "Pigeon Pea (Hybrid)",
    "Red Gram"
  ],
  "Pineapple Waste Meal": [
    "Pineapple Waste Meal (Standard)"
  ],
  "Pollard": [
    "Pollard (Standard)",
    "Pollard (Fine)",
    "Pollard (Coarse)"
  ],
  "Polyphenols (Grape Seed Extract)": [
    "Grape Seed Extract (OPC 95%)",
    "Pomegranate Polyphenol",
    "Resveratrol"
  ],
  "Porcine Hemoglobin": [
    "Porcine Hemoglobin (Spray-Dried)",
    "Deamidated Hemoglobin"
  ],
  "Porcine Liver Meal": [
    "Porcine Liver Meal (Standard)",
    "Porcine Liver Meal (Defatted)"
  ],
  "Porcine Plasma (Spray-Dried)": [
    "Spray-Dried Porcine Plasma (SDPP)",
    "Spray-Dried Porcine Plasma (Low IgG)"
  ],
  "Potassium Chloride": [
    "Potassium Chloride (Feed Grade)",
    "Potassium Chloride (Technical)"
  ],
  "Potato Protein": [
    "Potato Protein (Standard 80%)",
    "Potato Protein (HP 85%)"
  ],
  "Potato Pulp": [
    "Potato Pulp (Wet)",
    "Potato Pulp (Dried)"
  ],
  "Potato Starch": [
    "Potato Starch (Native)",
    "Potato Starch (Modified / Waxy)"
  ],
  "Poultry By-Product Meal": [
    "PBPM (Standard)",
    "PBPM (Low Ash)",
    "PBPM (Wet Rendered)"
  ],
  "Poultry Fat": [
    "Poultry Fat (Feed Grade)",
    "Poultry Fat (Refined)"
  ],
  "Poultry Offal Meal": [
    "Poultry Offal Meal (Standard)",
    "Poultry Offal Meal (Defatted)"
  ],
  "Precision Fermentation Protein": [
    "Precision Fermentation Protein (Yeast Platform)",
    "PF Protein (Bacterial Platform)"
  ],
  "Protease": [
    "Protease (Serine)",
    "Protease (Metalloprotease)",
    "Ronozyme ProAct"
  ],
  "Pumpkin Powder": [
    "Pumpkin Powder (Standard)",
    "Pumpkin Powder (Organic)"
  ],
  "Quinoa": [
    "White Quinoa",
    "Red Quinoa",
    "Black Quinoa",
    "Rainbow Quinoa"
  ],
  "Rapeseed (Full Fat)": [
    "Rapeseed Full-Fat (High GLS)",
    "Rapeseed Full-Fat (Low GLS)"
  ],
  "Rapeseed Cake": [
    "Rapeseed Cake (High GLS)",
    "Rapeseed Cake (Low GLS / 00)"
  ],
  "Rapeseed Lecithin": [
    "Rapeseed Lecithin (Fluid)",
    "Rapeseed Lecithin (Powder)"
  ],
  "Refined Glycerine": [
    "Refined Glycerine (99.5%)",
    "Refined Glycerine (USP Grade)"
  ],
  "Rice (Paddy / Brown)": [
    "Long Grain White",
    "Long Grain Brown",
    "Medium Grain",
    "Short Grain",
    "Parboiled",
    "Basmati",
    "Jasmine",
    "IR-64"
  ],
  "Rice Bran": [
    "Defatted Rice Bran",
    "Stabilized Rice Bran",
    "Full-Fat Rice Bran",
    "Parboiled Rice Bran"
  ],
  "Rice Flour": [
    "Rice Flour (White)",
    "Rice Flour (Brown)",
    "Rice Flour (Parboiled)"
  ],
  "Rice Husk / Hulls": [
    "Rice Husk (Raw)",
    "Rice Hull Ash",
    "Pelleted Rice Hulls"
  ],
  "Rice Polish": [
    "Rice Polish (Standard)",
    "Rice Polish (Fine)"
  ],
  "Rosemary Extract": [
    "Rosemary Extract (Liquid)",
    "Rosemary Extract (Powder)"
  ],
  "Rumen Contents (Dried)": [
    "Dried Rumen Contents (Standard)"
  ],
  "Rye": [
    "Winter Rye",
    "Spring Rye",
    "Hybrid Rye",
    "Diploid Rye",
    "Tetraploid Rye"
  ],
  "SCP from CO2 (Solar Foods Solein)": [
    "Solein (Solar Foods)",
    "Solein (CO2-derived)"
  ],
  "SCP from Methane (Calysta FeedKind)": [
    "FeedKind (Calysta SCP)",
    "FeedKind (Natural Gas-derived)"
  ],
  "Saccharomyces cerevisiae (Live Yeast)": [
    "Saccharomyces cerevisiae (Standard)",
    "S. cerevisiae (Chromium Enriched)",
    "DiamondV XP"
  ],
  "Safflower Meal": [
    "Safflower Meal (Decorticated 40% CP)",
    "Safflower Meal (Undecorticated 20% CP)"
  ],
  "Saponins (Yucca Extract)": [
    "Saponins Yucca schidigera (Standard)",
    "Yucca Extract (Liquid)"
  ],
  "Seaweed Meal (Kelp)": [
    "Kelp Meal (Ascophyllum nodosum)",
    "Kelp Meal (Laminaria)",
    "Sargassum Meal"
  ],
  "Selenium (Sodium Selenite)": [
    "Sodium Selenite (Standard)",
    "Selenium (Barium Selenate)"
  ],
  "Selenium Yeast": [
    "Selenium Yeast (2000 ppm)",
    "Selenium Yeast (1000 ppm)",
    "Sel-Plex"
  ],
  "Sesame Meal": [
    "Sesame Meal (Dehulled 48% CP)",
    "Sesame Meal (Whole Seed 40% CP)"
  ],
  "Sesame Oil": [
    "Crude Sesame Oil",
    "Cold-Pressed Sesame Oil",
    "Toasted Sesame Oil"
  ],
  "Shrimp Meal": [
    "Shrimp Meal (Whole)",
    "Shrimp Meal (Shell Only)",
    "Shrimp Meal (Head)"
  ],
  "Skim Milk Powder (SMP)": [
    "SMP (Extra Grade)",
    "SMP (Standard Grade)",
    "SMP (Low Heat)",
    "SMP (High Heat)"
  ],
  "Soap Stock": [
    "Soap Stock (Soy)",
    "Soap Stock (Palm)",
    "Soap Stock (Sunflower)"
  ],
  "Sodium Bentonite": [
    "Sodium Bentonite (Standard)",
    "Sodium Bentonite (HP Grade)"
  ],
  "Sodium Bicarbonate": [
    "Sodium Bicarbonate (Feed Grade)",
    "Sodium Bicarbonate (Technical)"
  ],
  "Sorghum / Milo": [
    "Red Sorghum",
    "White Sorghum",
    "Tan-Plant",
    "High-Tannin",
    "BMR (Brown Mid-Rib)",
    "Waxy",
    "High-Lysine"
  ],
  "Sorghum Bran": [
    "Sorghum Bran (Red)",
    "Sorghum Bran (White)"
  ],
  "Sorghum Flour": [
    "Sorghum Flour (Fine)",
    "Sorghum Flour (Whole Grain)"
  ],
  "Soy Lecithin": [
    "Soy Lecithin (Fluid)",
    "Soy Lecithin (Deoiled Powder)",
    "Soy Lecithin (Hydroxylated)"
  ],
  "Soy Oil": [
    "Crude Soy Oil",
    "RBD Soy Oil",
    "Degummed Soy Oil",
    "Refined Soy Oil"
  ],
  "Soy Protein Concentrate (SPC)": [
    "SPC 65%",
    "SPC 70% (HP)"
  ],
  "Soy Protein Isolate (SPI)": [
    "SPI 90% (Food Grade)",
    "SPI 90% (Feed Grade)"
  ],
  "Soybean (Whole)": [
    "Soybean Whole (Yellow)",
    "Soybean Whole (Black)",
    "Soybean Whole (Green)"
  ],
  "Soybean (Whole, Raw)": [
    "Commodity Non-GMO",
    "Commodity GMO",
    "Identity-Preserved (IP)",
    "Organic"
  ],
  "Soybean Hulls": [
    "Soy Hulls (Raw)",
    "Soy Hulls (Pelleted)"
  ],
  "Soybean Meal (HP, 48% CP)": [
    "SBM 48% CP (Hi-Pro)",
    "SBM 48% HP (Non-GMO)",
    "SBM 48% HP Organic"
  ],
  "Soybean Meal (Solvent Extracted, 44% CP)": [
    "SBM 44% CP (Standard)",
    "SBM 44% CP (Non-GMO)",
    "SBM 44% CP (Organic)"
  ],
  "Soybean Oil": [
    "Crude Soy Oil",
    "RBD Soy Oil",
    "Degummed Soy Oil"
  ],
  "Soybean Oil Cake (Expeller)": [
    "Soybean OC 45% CP",
    "Soybean OC 42% CP"
  ],
  "Spinach Powder": [
    "Spinach Powder (Standard)",
    "Spinach Powder (Freeze-Dried)"
  ],
  "Spirulina (Arthrospira platensis)": [
    "Spirulina (Food Grade)",
    "Spirulina (Feed Grade)",
    "Spirulina (Organic)"
  ],
  "Spray-Dried Fish Solubles": [
    "Spray-Dried Fish Solubles (Standard)",
    "Spray-Dried Fish Solubles (Low Ash)"
  ],
  "Squid Meal": [
    "Squid Meal (Standard)",
    "Squid Meal (Low-Temperature)"
  ],
  "Squid Oil": [
    "Squid Oil (Crude)",
    "Squid Oil (Refined)"
  ],
  "Sucrose": [
    "Refined White Sugar",
    "Raw Cane Sugar",
    "Brown Sugar"
  ],
  "Sugar Beet Molasses": [
    "Sugar Beet Molasses (Standard)",
    "Beet Molasses (Low Sugar)"
  ],
  "Sugarcane Tops & Leaves": [
    "Sugarcane Tops (Fresh)",
    "Sugarcane Tops (Dried)"
  ],
  "Sunflower Cake (Expeller)": [
    "Sunflower Cake Expeller 25% CP",
    "Sunflower Cake 30% CP"
  ],
  "Sunflower Hulls": [
    "Sunflower Hulls (Raw)",
    "Sunflower Hulls (Ground)"
  ],
  "Sunflower Lecithin": [
    "Sunflower Lecithin (Fluid)",
    "Sunflower Lecithin (Powder)"
  ],
  "Sunflower Meal (Decorticated)": [
    "Sunflower Meal Dec. 28% CP",
    "Sunflower Meal Dec. 35% CP",
    "Non-Decorticated"
  ],
  "Sunflower Oil": [
    "Crude Sunflower Oil",
    "RBD Sunflower Oil",
    "High-Oleic"
  ],
  "Sunflower Seed": [
    "Confection Sunflower",
    "Oil-Type Sunflower",
    "Striped Sunflower",
    "High-Oleic Sunflower"
  ],
  "Sweet Potato Flour": [
    "Sweet Potato Flour (Orange)",
    "Sweet Potato Flour (White/Purple)"
  ],
  "Sweet Potato Starch": [
    "Sweet Potato Starch (Native)",
    "Sweet Potato Starch (Modified)"
  ],
  "Tallow (Beef)": [
    "Beef Tallow (Edible)",
    "Beef Tallow (Inedible)",
    "RBD Tallow"
  ],
  "Tapioca Starch": [
    "Tapioca Starch (Native)",
    "Tapioca Starch (Modified)"
  ],
  "Taurine": [
    "Taurine (Feed Grade 99%)",
    "Taurine (Synthetic 99%)"
  ],
  "Tea Waste / Grounds": [
    "Tea Waste (Green Tea)",
    "Tea Waste (Black Tea)",
    "Tea Grounds"
  ],
  "Teff": [
    "White Teff",
    "Brown/Red Teff",
    "Mixed Teff"
  ],
  "Thraustochytrid DHA Oil": [
    "Aurantiochytrium (DHA 20%)",
    "Schizochytrium (DHA 30%)"
  ],
  "Thyme Powder": [
    "Thyme Powder (Thymus vulgaris)",
    "Thyme Powder (Organic)"
  ],
  "Thymol": [
    "Thymol (Standard 98%)",
    "Thymol (Pharma Grade)"
  ],
  "Tomato Pomace": [
    "Tomato Pomace (Dried)",
    "Tomato Seed Meal"
  ],
  "Torula Yeast": [
    "Torula Yeast (Standard)",
    "Torula Yeast (Chromium-Enriched)"
  ],
  "Tricalcium Phosphate (TCP)": [
    "TCP (Feed Grade)",
    "TCP (HP 20% P)"
  ],
  "Trimethylamine Oxide (TMAO)": [
    "TMAO (Standard)",
    "TMAO (Synthetic)"
  ],
  "Triticale": [
    "Spring Triticale",
    "Winter Triticale",
    "Hexaploid",
    "Octaploid"
  ],
  "Turmeric Powder": [
    "Turmeric (Curcuma longa)",
    "Turmeric (High Curcumin >5%)",
    "Turmeric (Organic)"
  ],
  "Vinasse": [
    "Vinasse (Cane)",
    "Vinasse (Beet)",
    "Condensed Vinasse"
  ],
  "Vitamin A (Retinyl Acetate)": [
    "Retinyl Acetate (500,000 IU/g)",
    "Retinyl Palmitate (1,000,000 IU/g)"
  ],
  "Vitamin B1 (Thiamine)": [
    "Thiamine Mononitrate",
    "Thiamine HCl"
  ],
  "Vitamin B12 (Cyanocobalamin)": [
    "Cyanocobalamin (1%)",
    "Hydroxocobalamin (0.1%)"
  ],
  "Vitamin B2 (Riboflavin)": [
    "Riboflavin (Feed Grade 80%)",
    "Riboflavin (Technical 98%)"
  ],
  "Vitamin B3 (Niacin)": [
    "Niacin (Nicotinic Acid)",
    "Niacinamide (Nicotinamide)"
  ],
  "Vitamin B5 (Pantothenic Acid)": [
    "Calcium D-Pantothenate (Feed Grade)",
    "D-Panthenol"
  ],
  "Vitamin B6 (Pyridoxine)": [
    "Pyridoxine HCl (Feed Grade)",
    "Pyridoxal-5-Phosphate"
  ],
  "Vitamin B7 (Biotin)": [
    "D-Biotin (2%)",
    "D-Biotin (1%)"
  ],
  "Vitamin B9 (Folic Acid)": [
    "Folic Acid (Feed Grade 80%)",
    "Folic Acid (Technical 96%)"
  ],
  "Vitamin C (Ascorbic Acid)": [
    "Ascorbic Acid (L-AA)",
    "Ascorbyl-2-Polyphosphate (APP)",
    "Sodium Ascorbate"
  ],
  "Vitamin C (Stabilized)": [
    "Vitamin C Stabilized (Ascorbyl Polyphosphate)",
    "Vitamin C (Monophosphate)"
  ],
  "Vitamin D3 (Cholecalciferol)": [
    "Cholecalciferol (500,000 IU/g)",
    "Cholecalciferol (1,000,000 IU/g)"
  ],
  "Vitamin E (dl-Alpha-Tocopheryl Acetate)": [
    "dl-Alpha-Tocopheryl Acetate (50%)",
    "d-Alpha-Tocopheryl Acetate (Natural)"
  ],
  "Vitamin K3 (Menadione)": [
    "Menadione Sodium Bisulfite (MSB)",
    "Menadione Nicotinamide Bisulfite (MNB)"
  ],
  "Wet Brewers Grains": [
    "Wet Brewers Grains (Standard)",
    "Wet BG (Ensiled)"
  ],
  "Wet Distillers Grains": [
    "Wet Distillers Grains (WDG)",
    "Wet DG with Solubles (WDGS)"
  ],
  "Wheat": [
    "Hard Red Winter (HRW)",
    "Hard Red Spring (HRS)",
    "Soft Red Winter (SRW)",
    "Hard White (HW)",
    "Soft White (SW)",
    "Durum"
  ],
  "Wheat Bran": [
    "Fine Wheat Bran",
    "Coarse Wheat Bran",
    "Super Bran",
    "Stabilized Bran"
  ],
  "Wheat Flour (Feed Grade)": [
    "Feed Grade (Low Protein)",
    "Feed Grade (Medium Protein)"
  ],
  "Wheat Germ": [
    "Defatted Wheat Germ",
    "Full-Fat Wheat Germ",
    "Toasted Wheat Germ"
  ],
  "Wheat Gluten (Vital)": [
    "Wheat Gluten Vital (Standard)",
    "Wheat Gluten Vital (HP)"
  ],
  "Wheat Middlings": [
    "Middlings (Fine)",
    "Middlings (Coarse)",
    "Red Middlings"
  ],
  "Wheat Shorts": [
    "Fine Shorts",
    "Coarse Shorts",
    "Red Dog Shorts"
  ],
  "Wheat Starch": [
    "Wheat Starch (A-Starch)",
    "Wheat Starch (B-Starch)"
  ],
  "Whey Powder": [
    "Sweet Whey Powder",
    "Acid Whey Powder",
    "Demineralized Whey (70% DEM)",
    "Demineralized Whey (90% DEM)"
  ],
  "Whey Protein Concentrate (WPC)": [
    "WPC 35%",
    "WPC 50%",
    "WPC 65%",
    "WPC 80%"
  ],
  "Whey Protein Isolate (WPI)": [
    "WPI 90% (Micro-filtered)",
    "WPI 92% (Ion-Exchanged)"
  ],
  "Whole Egg Powder": [
    "Whole Egg Powder (Spray-Dried)",
    "Whole Egg Powder (Freeze-Dried)"
  ],
  "Whole Milk Powder (WMP)": [
    "WMP (Standard 26% Fat)",
    "WMP (Low Fat)",
    "WMP (Instant)"
  ],
  "Xylanase": [
    "Xylanase (Trichoderma)",
    "Xylanase (Bacillus)",
    "Econase XT"
  ],
  "Yam Flour": [
    "Yam Flour (White Yam)",
    "Yam Flour (Water Yam)",
    "Yam Flour (Yellow Yam)"
  ],
  "Yeast Cell Wall": [
    "Yeast Cell Wall (Standard)",
    "Yeast Cell Wall (HP MOS)"
  ],
  "Yeast Extract": [
    "Yeast Extract (Standard)",
    "Yeast Extract (Autolyzed)",
    "Yeast Extract (Low Sodium)"
  ],
  "Yellow Grease": [
    "Yellow Grease (Standard)",
    "Yellow Grease (Filtered)"
  ],
  "Zinc Methionine": [
    "Zinc Methionine (Availa-Zn)",
    "Zinc Methionine Complex"
  ],
  "Zinc Oxide": [
    "Zinc Oxide (Feed Grade 72%)",
    "Zinc Oxide (HP 80%)"
  ],
  "Zinc Sulfate": [
    "Zinc Sulfate (Monohydrate)",
    "Zinc Sulfate (Heptahydrate)"
  ]
}''';
