class ProductCatalogData {
  ProductCatalogData._();

  static const Map<String, Map<String, List<String>>> catalog = {
    'Grains & Cereals': {
      'Grains': [
        'Maize / Corn',
        'Wheat',
        'Barley',
        'Sorghum / Milo',
        'Oats',
        'Rye',
        'Triticale',
        'Millet (Pearl)',
        'Millet (Finger / Ragi)',
        'Rice (Paddy / Brown)',
        'Buckwheat',
        'Teff',
        'Amaranth Grain',
        'Quinoa',
        'Canary Seed',
      ],
    },
    'Flour & Milling By-Products': {
      'Wheat By-Products': [
        'Wheat Bran',
        'Wheat Shorts',
        'Wheat Middlings',
        'Wheat Germ',
        'Wheat Flour (Feed Grade)',
        'Pollard',
      ],
      'Rice By-Products': [
        'Rice Bran',
        'Rice Polish',
        'Rice Husk / Hulls',
        'Broken Rice',
        'Rice Flour',
      ],
      'Maize By-Products': [
        'Maize Bran',
        'Maize Germ',
        'Hominy Feed',
        'Corn Gluten Feed',
        'Corn Gluten Meal',
        'Corn Steep Liquor',
        'Maize Flour',
      ],
      'Sorghum By-Products': [
        'Sorghum Bran',
        'Sorghum Flour',
      ],
      'Barley By-Products': [
        'Barley Bran',
        'Barley Flour',
      ],
      'Oat By-Products': [
        'Oat Bran',
        'Oat Hulls',
        'Oat Feed',
      ],
    },
    'Oilseeds & Oil Cakes': {
      'Soybean Products': [
        'Soybean (Whole, Raw)',
        'Full-Fat Soybean (Extruded)',
        'Soybean Meal (Solvent Extracted, 44% CP)',
        'Soybean Meal (HP, 48% CP)',
        'Soybean Oil Cake (Expeller)',
        'Soy Protein Concentrate (SPC)',
        'Soy Protein Isolate (SPI)',
        'Soybean Hulls',
        'Soy Oil',
      ],
      'Sunflower Products': [
        'Sunflower Seed',
        'Sunflower Meal (Decorticated)',
        'Sunflower Cake (Expeller)',
        'Sunflower Oil',
        'Sunflower Hulls',
      ],
      'Canola / Rapeseed Products': [
        'Canola Meal',
        'Rapeseed Cake',
        'Canola Oil',
        'Rapeseed (Full Fat)',
      ],
      'Cottonseed Products': [
        'Cottonseed Meal',
        'Cottonseed Cake',
        'Cottonseed Oil',
        'Cottonseed Hulls',
      ],
      'Groundnut / Peanut Products': [
        'Groundnut Meal',
        'Groundnut Cake (Expeller)',
        'Groundnut Oil',
        'Groundnut Hulls',
      ],
      'Palm Products': [
        'Palm Kernel Cake (PKC)',
        'Palm Kernel Meal',
        'Palm Kernel Oil',
        'Crude Palm Oil (CPO)',
        'Palm Oil Sludge / POME',
      ],
      'Linseed / Flaxseed Products': [
        'Linseed Meal',
        'Linseed Cake',
        'Linseed Oil',
      ],
      'Other Oilseeds': [
        'Sesame Meal',
        'Sesame Oil',
        'Copra Meal',
        'Coconut Oil',
        'Mustard Seed Cake',
        'Safflower Meal',
        'Camelina Meal',
      ],
    },
    'Animal Protein Sources': {
      'Meat & Bone Products': [
        'Meat and Bone Meal (MBM)',
        'Meat Meal',
        'Blood Meal',
        'Feather Meal (Hydrolyzed)',
        'Poultry By-Product Meal',
        'Poultry Offal Meal',
        'Hydrolyzed Leather Meal',
        'Bone Meal (Steamed)',
        'Tallow (Beef)',
        'Lard / Pork Fat',
        'Poultry Fat',
      ],
      'Porcine Products': [
        'Porcine Plasma (Spray-Dried)',
        'Porcine Hemoglobin',
        'Porcine Liver Meal',
      ],
      'Ruminant Products': [
        'Dried Whey',
        'Casein',
        'Rumen Contents (Dried)',
      ],
    },
    'Marine & Aquatic Ingredients': {
      'Fish Meals': [
        'Fish Meal (Anchovy, 65% CP)',
        'Fish Meal (Menhaden)',
        'Fish Meal (Sardine)',
        'Fish Meal (Herring)',
        'Fish Meal (Tilapia By-Product)',
        'Fish Meal (Catfish By-Product)',
        'Fish Meal (Low Temperature, LT)',
        'Fish Meal (Super Prime)',
      ],
      'Fish Oils': [
        'Fish Oil (Anchovy)',
        'Fish Oil (Salmon)',
        'Fish Oil (Menhaden)',
        'Fish Oil (Refined, EPA/DHA enriched)',
      ],
      'Fish Hydrolysates & Solubles': [
        'Fish Protein Hydrolysate (FPH)',
        'Fish Solubles (Condensed)',
        'Spray-Dried Fish Solubles',
      ],
      'Crustacean & Shellfish Products': [
        'Shrimp Meal',
        'Krill Meal',
        'Krill Oil',
        'Crab Meal',
        'Squid Meal',
        'Squid Oil',
        'Oyster Shell Meal',
      ],
      'Algae & Seaweed': [
        'Spirulina (Arthrospira platensis)',
        'Chlorella',
        'Nannochloropsis',
        'Thraustochytrid DHA Oil',
        'Seaweed Meal (Kelp)',
        'Agar / Carrageenan',
      ],
    },
    'Legumes & Pulses': {
      'Beans': [
        'Soybean (Whole)',
        'Field Beans / Faba Beans',
        'Mung Beans',
      ],
      'Peas': [
        'Field Peas',
        'Pea Protein Concentrate',
        'Pea Starch',
        'Pea Hull / Fibre',
      ],
      'Lentils & Others': [
        'Lentils',
        'Chickpeas / Garbanzo Beans',
        'Lupins (Sweet)',
        'Cowpeas',
        'Pigeon Peas (Toor Dal)',
        'Guar Meal',
      ],
    },
    'Roots, Tubers & Starches': {
      'Cassava Products': [
        'Cassava Chips (Dried)',
        'Cassava Flour',
        'Cassava Starch',
        'Cassava Pellets',
        'Cassava Peels (Dried)',
      ],
      'Potato Products': [
        'Potato Starch',
        'Potato Protein',
        'Potato Pulp',
        'Dried Potato Flakes',
      ],
      'Sweet Potato': [
        'Sweet Potato Flour',
        'Sweet Potato Starch',
      ],
      'Yam': [
        'Yam Flour',
      ],
      'Other Starches': [
        'Tapioca Starch',
        'Corn Starch',
        'Wheat Starch',
        'Modified Starch',
      ],
    },
    'Sugar & Molasses By-Products': {
      'Sugarcane By-Products': [
        'Molasses (Sugarcane)',
        'Bagasse',
        'Sugarcane Tops & Leaves',
        'Filter Cake / Press Mud',
        'Cane Juice',
      ],
      'Beet By-Products': [
        'Sugar Beet Molasses',
        'Dried Beet Pulp',
        'Vinasse',
      ],
      'Refined Sugar Products': [
        'Sucrose',
        'Glucose / Dextrose',
        'Lactose',
      ],
    },
    'Fats, Oils & Lipids': {
      'Vegetable Oils': [
        'Soybean Oil',
        'Sunflower Oil',
        'Canola / Rapeseed Oil',
        'Palm Oil (RBD)',
        'Corn Oil',
        'Coconut Oil',
        'Cottonseed Oil',
      ],
      'Animal Fats': [
        'Beef Tallow',
        'Lard',
        'Poultry Fat',
        'Yellow Grease',
        'Choice White Grease (CWG)',
      ],
      'Lecithins & Emulsifiers': [
        'Soy Lecithin',
        'Sunflower Lecithin',
        'Rapeseed Lecithin',
      ],
    },
    'Dairy & Egg Ingredients': {
      'Milk Products': [
        'Skim Milk Powder (SMP)',
        'Whole Milk Powder (WMP)',
        'Whey Powder',
        'Whey Protein Concentrate (WPC)',
        'Whey Protein Isolate (WPI)',
        'Lactose',
        'Casein',
        'Milk Replacer',
        'Butter / Butter Oil',
      ],
      'Egg Products': [
        'Whole Egg Powder',
        'Egg White Powder / Albumen',
        'Egg Yolk Powder',
        'Dried Whole Egg',
      ],
    },
    'Fruits & Vegetables (Processed)': {
      'Fruit By-Products': [
        'Citrus Pulp (Dried)',
        'Apple Pomace (Dried)',
        'Grape Pomace',
        'Tomato Pomace',
        'Mango Kernel Flour',
        'Banana Flour / Peel',
        'Pineapple Waste Meal',
      ],
      'Vegetable By-Products': [
        'Alfalfa Meal',
        'Dried Lucerne / Hay',
        'Beetroot Powder',
        'Carrot Powder',
        'Spinach Powder',
        'Pumpkin Powder',
      ],
    },
    'Feed Additives & Supplements': {
      'Enzymes': [
        'Phytase',
        'Xylanase',
        'Amylase',
        'Protease',
        'Lipase',
        'Beta-glucanase',
        'Cellulase',
      ],
      'Probiotics & Prebiotics': [
        'Saccharomyces cerevisiae (Live Yeast)',
        'Bacillus subtilis',
        'Lactobacillus acidophilus',
        'MOS (Mannan-Oligosaccharides)',
        'FOS (Fructo-Oligosaccharides)',
        'Beta-Glucan',
      ],
      'Antioxidants': [
        'Ethoxyquin (EQ)',
        'BHA (Butylated Hydroxyanisole)',
        'BHT (Butylated Hydroxytoluene)',
        'Natural Vitamin E (Tocopherol)',
        'Rosemary Extract',
      ],
      'Binders & Pellet Aids': [
        'Bentonite',
        'Guar Gum',
        'Lignosulfonate',
        'CMC (Carboxymethyl Cellulose)',
        'Sodium Bentonite',
      ],
      'Attractants & Palatants': [
        'Betaine (Natural)',
        'Betaine HCl (Synthetic)',
        'Trimethylamine Oxide (TMAO)',
        'Nucleotides',
        'Inosine Monophosphate (IMP)',
        'Dimethyl Sulfoxide (DMSO)',
      ],
      'Growth Promoters': [
        'Organic Acids (Formic, Propionic)',
        'Butyric Acid / Tributyrin',
        'Humic Acids',
        'Fulvic Acids',
      ],
      'Immunostimulants': [
        'Beta-1,3/1,6-Glucan',
        'Vitamin C (Ascorbic Acid)',
        'Astaxanthin',
        'Canthaxanthin',
      ],
    },
    'Minerals & Salts': {
      'Macro Minerals': [
        'Dicalcium Phosphate (DCP)',
        'Monocalcium Phosphate (MCP)',
        'Tricalcium Phosphate (TCP)',
        'Limestone Flour (CaCO3)',
        'Oyster Shell Flour',
        'Common Salt (NaCl)',
        'Sodium Bicarbonate',
        'Magnesium Oxide (MgO)',
        'Potassium Chloride',
      ],
      'Trace Minerals': [
        'Zinc Sulfate',
        'Zinc Oxide',
        'Manganese Sulfate',
        'Copper Sulfate',
        'Ferrous Sulfate',
        'Selenium (Sodium Selenite)',
        'Selenium Yeast',
        'Iodine (Potassium Iodide)',
        'Cobalt Sulfate',
        'Chromium Picolinate',
      ],
      'Organic Trace Minerals': [
        'Zinc Methionine',
        'Manganese Methionine',
        'Copper Proteinate',
        'Iron Proteinate',
      ],
    },
    'Vitamins & Amino Acids': {
      'Fat-Soluble Vitamins': [
        'Vitamin A (Retinyl Acetate)',
        'Vitamin D3 (Cholecalciferol)',
        'Vitamin E (dl-Alpha-Tocopheryl Acetate)',
        'Vitamin K3 (Menadione)',
      ],
      'Water-Soluble Vitamins': [
        'Vitamin B1 (Thiamine)',
        'Vitamin B2 (Riboflavin)',
        'Vitamin B3 (Niacin)',
        'Vitamin B5 (Pantothenic Acid)',
        'Vitamin B6 (Pyridoxine)',
        'Vitamin B7 (Biotin)',
        'Vitamin B9 (Folic Acid)',
        'Vitamin B12 (Cyanocobalamin)',
        'Vitamin C (Ascorbic Acid)',
      ],
      'Amino Acids': [
        'L-Lysine HCl',
        'DL-Methionine',
        'L-Threonine',
        'L-Tryptophan',
        'L-Valine',
        'L-Isoleucine',
        'L-Leucine',
        'L-Arginine',
        'Taurine',
        'Glycine',
        'L-Glutamine',
      ],
    },
    'Fermentation & Biotech Ingredients': {
      'Yeast Products': [
        "Brewer's Yeast (Dried)",
        "Baker's Yeast",
        'Torula Yeast',
        'Yeast Extract',
        'Yeast Cell Wall',
        'Autolyzed Yeast',
      ],
      'Single Cell Proteins': [
        'SCP from Methane (Calysta FeedKind)',
        'SCP from CO2 (Solar Foods Solein)',
        'Fermented Soybean Meal',
        'Mycoprotein (Quorn)',
      ],
      'DDGS & Distillery By-Products': [
        'DDGS (Corn, Distillers Dried Grains with Solubles)',
        'DDGS (Wheat)',
        'DDGS (Barley)',
        'Wet Distillers Grains',
      ],
    },
    'Industrial & Novel Proteins': {
      'Insect Meals': [
        'Black Soldier Fly Larvae Meal (BSFL)',
        'Mealworm Meal (Tenebrio molitor)',
        'Cricket Meal',
        'Housefly Larvae Meal',
      ],
      'Insect Oils': [
        'BSFL Oil',
        'Mealworm Oil',
      ],
      'Plant-Based Novel Proteins': [
        'Duckweed Meal',
        'Moringa Leaf Meal',
        'Hemp Protein Meal',
        'Chickpea Protein',
      ],
      'Cultivated & Lab Proteins': [
        'Precision Fermentation Protein',
        'Cell-Cultured Protein',
      ],
    },
    'Spices, Herbs & Botanicals': {
      'Spices': [
        'Turmeric Powder',
        'Black Pepper',
        'Chili / Capsicum',
        'Ginger Powder',
        'Garlic Powder',
        'Cinnamon Powder',
        'Cumin / Jeera',
      ],
      'Herbs': [
        'Oregano Powder',
        'Thyme Powder',
        'Rosemary Extract',
      ],
      'Phytogenics / Plant Extracts': [
        'Thymol',
        'Carvacrol',
        'Cinnamaldehyde',
        'Saponins (Yucca Extract)',
        'Polyphenols (Grape Seed Extract)',
      ],
    },
    'Beverages & Brewery By-Products': {
      'Brewery By-Products': [
        'Dried Brewers Grains',
        'Wet Brewers Grains',
        'Brewers Yeast (Dried)',
        'Hops Residue',
        'Malt Culms / Sprouts',
      ],
      'Coffee & Cocoa By-Products': [
        'Coffee Husks',
        'Cocoa Husks',
        'Cocoa Pod Husk',
      ],
      'Tea By-Products': [
        'Tea Waste / Grounds',
      ],
    },
    'Food Processing By-Products': {
      'Bakery By-Products': [
        'Bakery Meal / Waste',
        'Bread Crumbs',
        'Cookie / Biscuit Waste',
        'Pasta Waste',
      ],
      'Vegetable Oil Processing': [
        'Acid Oil / Fatty Acid Distillate',
        'Soap Stock',
        'Glycerol / Glycerine (Crude)',
        'Refined Glycerine',
      ],
      'Starch Processing': [
        'Corn Steep Liquor',
        'Corn Fiber',
        'Modified Starch',
      ],
    },
    'Aquaculture-Specific Ingredients': {
      'Pigments & Colorants': [
        'Astaxanthin (Synthetic)',
        'Astaxanthin (Natural, Haematococcus)',
        'Canthaxanthin',
        'Lutein',
        'Beta-Carotene',
      ],
      'Immune & Health Additives': [
        'Nucleotides (Feed Grade)',
        'Garlic Extract (Allicin)',
        'Beta-Glucan (Yeast)',
        'Vitamin C (Stabilized)',
        'Organic Selenium',
      ],
      'Specific Aqua Binders': [
        'Carrageenan',
        'Guar Gum',
        'Wheat Gluten (Vital)',
        'CMC',
        'Modified Starch (Waxy Maize)',
      ],
      'Water Stability Enhancers': [
        'Choline Chloride',
        'Inositol',
        'Taurine',
      ],
    },
  };
}
