import 'dart:convert';
import 'dart:io';

/// Split "Varieties: ..." line respecting parentheses nesting.
List<String> splitVarietiesLine(String afterPrefix) {
  final input = afterPrefix.trim();
  if (input.isEmpty) return const [];
  final out = <String>[];
  final buf = StringBuffer();
  var depth = 0;
  for (var i = 0; i < input.length; i++) {
    final c = input[i];
    if (c == '(') {
      depth++;
    } else if (c == ')') {
      depth = depth > 0 ? depth - 1 : 0;
    }
    if (c == ',' && depth == 0) {
      final s = buf.toString().trim();
      if (s.isNotEmpty) out.add(s);
      buf.clear();
      if (i + 1 < input.length && input[i + 1] == ' ') {
        i++;
      }
      continue;
    }
    buf.write(c);
  }
  final tail = buf.toString().trim();
  if (tail.isNotEmpty) out.add(tail);
  return out;
}

Map<String, List<String>> parseUserVarietiesFile(String raw) {
  var text = raw.trim();
  if (text.startsWith('<user_query>')) {
    text = text.substring('<user_query>'.length).trim();
  }
  if (text.endsWith('</user_query>')) {
    text = text.substring(0, text.length - '</user_query>'.length).trim();
  }
  final lines = text.split('\n').map((e) => e.trim()).toList();
  final map = <String, List<String>>{};
  for (var i = 0; i < lines.length; i++) {
    final line = lines[i];
    if (line.isEmpty) continue;
    if (line.startsWith('<')) continue;
    if (line.startsWith('Varieties:')) {
      continue;
    }
    if (i + 1 < lines.length && lines[i + 1].startsWith('Varieties:')) {
      final vLine = lines[i + 1];
      final vRaw = vLine.substring('Varieties:'.length).trim();
      map[line] = splitVarietiesLine(vRaw);
    }
  }
  return map;
}

void main() {
  final userPath = File('tool/user_varieties_message.txt');
  final catalogPath = File('tool/catalog_names_clean.txt');
  if (!userPath.existsSync()) {
    stderr.writeln('Missing ${userPath.path}');
    exit(1);
  }
  if (!catalogPath.existsSync()) {
    stderr.writeln('Missing ${catalogPath.path} — run dart run tool/_list_names.dart');
    exit(1);
  }
  final userMap = parseUserVarietiesFile(userPath.readAsStringSync());
  final catalogNames = catalogPath
      .readAsLinesSync()
      .map((e) => e.trim())
      .where((e) => e.isNotEmpty)
      .toList();

  final merged = <String, List<String>>{};
  for (final name in catalogNames) {
    final v = userMap[name];
    if (v != null && v.isNotEmpty) {
      merged[name] = List<String>.from(v);
    } else {
      merged[name] = const ['Standard'];
    }
  }

  for (final k in userMap.keys) {
    if (!catalogNames.contains(k)) {
      stderr.writeln('WARN: user variety key not in catalog: $k');
    }
  }

  final jsonObj = merged.map((k, v) => MapEntry(k, v));
  final jsonText = const JsonEncoder.withIndent('  ').convert(jsonObj);

  final outPath =
      File('lib/features/seller/add_product/product_varieties_embed.generated.dart');
  final sink = outPath.openWrite();
  sink.writeln('// GENERATED by tool/build_varieties_dart.dart — do not edit by hand.');
  sink.writeln("import 'dart:convert';");
  sink.writeln();
  sink.writeln('Map<String, List<String>>? _productVarietiesCache;');
  sink.writeln();
  sink.writeln('Map<String, List<String>> productVarietiesByName() {');
  sink.writeln('  return _productVarietiesCache ??=');
  sink.writeln('      (jsonDecode(_productVarietiesJson) as Map<String, dynamic>)');
  sink.writeln('          .map((k, v) => MapEntry(');
  sink.writeln('            k,');
  sink.writeln('            List<String>.from(v as List<dynamic>),');
  sink.writeln('          ));');
  sink.writeln('}');
  sink.writeln();
  sink.writeln("const String _productVarietiesJson = r'''");
  sink.write(jsonText);
  sink.writeln("''';");
  sink.close();

  stdout.writeln('Wrote ${outPath.path} (${merged.length} products)');
}
